- name: Show credentials from vault
  hosts: all
  gather_facts: false
  tasks:
  
    - name: Display Username from Vault
      debug:
        msg: "{{ ansible_user }}"
        
    - name: Check ip 
      debug:
        msg: "{{ ansible_fqdn }}"
        
    - name: Test connection to host
      ping:  
