- name: Show credentials from vault
  hosts: all
  gather_facts: false
  vars:
    - password: '{{ ansible_password }}'
  tasks:
  
    - name: Display Username from Vault
      debug:
        msg: "{{ ansible_user }}"
        
    - name: Test
      shell:
        cmd: ifconfig
